<?php
$config['full_tag_open'] = '<div class="text-center mt24"><ul class="pagination">';
$config['full_tag_close'] = '</ul></div>';
$config['first_link'] = '<span aria-hidden="true">&laquo;</span>';
$config['last_link'] = '<span aria-hidden="true">&raquo;</span>';
$config['first_tag_open'] = '<li>';
$config['first_tag_close'] = '</li>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';
$config['last_tag_open'] = '<li>';
$config['last_tag_close'] = '</li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
$config['prev_link'] = false;
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';
$config['cur_tag_open'] = '<li class="active"><a href="#">';
$config['cur_tag_close'] = '</li></a>';
$config['next_link'] = false;
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';
$config['use_page_numbers'] = TRUE;
$config['per_page'] = 10;
$config['num_links'] = 5;
